config/routes.rb
Rails.application.routes.draw do

  @web = { domain: ["tripkada.com","localhost", "13.250.138.152", "13.229.186.20"] } unless Rails.env.development? || Rails.env.test?
  @api = { subdomain: ["staging-api","api"] } unless Rails.env.development? || Rails.env.test?

  mount Facebook::Messenger::Server, at: 'bot'
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  constraints @api do
    mount API::Base => '/'
  end

  constraints @web do
    authenticate :user do

      scope :profile do
        post "/:slug/reviews",    to: "users#review",                   as: "profile_review"
        get "/:slug/edit",        to: "users#edit",                     as: "profile_edit"
        put "/:slug",             to: "users#update_profile_photos",    as: "profile_update"
        post "/:slug/follow",     to: "users#follow",                   as: "follow_user"
        delete "/:slug/unfollow", to: "users#unfollow",                 as: "unfollow_user"
      end

      scope :trips do
        get "/:slug/checkout",                                to: "event#checkout",                       as: "trip_checkout"
        get "/waitlists/:id/checkout",                        to: "event#waitlist_checkout",              as: "waitlist_checkout"
        get "/:slug/checkout/payment_details",                to: "event#payment_details",                as: "payment_details"
        get "/:slug/checkout/paypal_payment_verification",    to: "payments#paypal_payment_verification", as: "paypal_payment_verification"
        post "/:slug/join",                                   to: "event#join",                           as: "join"
        post "/:slug/join_using_promo_code",                  to: "event#join_using_promo_code",          as: "join_using_promo_code"
        post "/promo_code/validate",                          to: "promo_codes#validate",                 as: "validate_promo_code"
        post "/:slug/join_waitlist",                          to: "event#join_waitlist",                  as: "join_waitlist"
        get  "/:slug/checkout/dragonpay",                     to: "event#dragonpay",                      as: "dragonpay"
      end

      scope :organizer do
        get "/trips/:slug/edit",                      to: "event#edit",               as: "organizer_trip_edit"
        get "/trips/:slug/duplicate",                 to: "event#duplicate",          as: "organizer_trip_duplicate"
        put "/trips/:slug",                           to: "event#update",             as: "organizer_trips"
        delete "/trips/:slug",                        to: "event#destroy"
        get "/create_trip",                           to: "event#new"
        post "/create_trip",                          to: "event#create"
        put "/trip_no_show",                          to: "event#no_show",            as: "trip_no_show"
        scope :manage_trips do
          get "/",                                    to: "manage_trips#index",        as: "manage_trips"
          get "/my_trips",                            to: "manage_trips#trips",        as: "manage_trips_my_trips"
          get "/my_trips/:slug/waitlists",            to: "manage_trips#waitlists",    as: "manage_trips_waitlist"
          put "/my_trips/:slug/cancel",               to: "manage_trips#cancel_trip",  as: "organizer_trip_cancel"
          get "/joiner",                              to: "manage_trips#joiner",       as: "manage_trips_joiner"
          get "/payments",                            to: "manage_trips#payments",     as: "manage_trips_payments"
          get "/funds",                               to: "manage_trips#funds",        as: "manage_trips_funds"
          post "/invite_joiner",                      to: "manage_trips#invite_joiner", as: "organizer_invite_joiner"
          post "/invite_joiner_via_email",            to: "manage_trips#invite_joiner_via_email", as: "organizer_invite_joiner_via_email"
          get "organized_trip_views",                 to: "manage_trips#organized_trip_views"
          get "organized_trip_bookings",              to: "manage_trips#organized_trip_bookings"
          get "monthly_organized_trips",                      to: "manage_trips#monthly_organized_trips"
          get "monthly_organized_trips_booking_count",        to: "manage_trips#monthly_organized_trips_booking_count"

          post 'my_trips/waitlists/update_waitlist',  to: "manage_trips#update_waitlist", as: "update_waitlist"
        end
      end

      scope :admin do
        get "/",                                            to: "admin#index",                                     as: "admin"
        get "/event/:slug",                                 to: "admin#event",                                     as: "get_event"
        get "/users",                                       to: "users#index"
        get "/users/organizer_applicants",                  to: "users#organizer_applicants",                      as: "organizer_applicants"
        get "/users/export_all_organizers",                 to: "users#export_all_organizers",                     as: "export_all_organizers"
        get "/users/export_stats_organizer",                to: "users#export_stats_organizer",                    as: "export_stats_organizer"
        get "/users/cities",                                to: "users#cities"
        get "/users/export",                                to: "users#export",                                    as: "export_users"
        get "/users/segmentations",                         to: "users#segmentations",                             as: "user_segmentations"
        get "/users/export_segmentations",                  to: "users#export_segmentations",                      as: "export_users_segmentation"
        get "/payments/export_all_payments",                to: "payments#export_all_payments",                    as: "export_all_payments"
        get "/users/user_info",                             to: "users#user_info",                                 as: "user_info"
        get "/payments/mark_expired",                       to: "payments#mark_dragonpay_as_expired",              as: "mark_expired_payments"

        delete "/remove_joiner",                            to: "admin#remove_joiner"
        put "/users/:id/update_role",                       to: "users#update_role",                               as: "update_role"
        put "/event/featured",                              to: "admin#make_featured",                             as: "make_featured"
        get "/mailerlite/groups",                           to: "mailerlite#index",                                as: "mailerlite_groups"
        post "/mailerlite/groups",                          to: "mailerlite#create",                               as: "mailerlite_new_group"
        post "/mailerlite/groups/:id/import_subscribers",   to: "mailerlite#import_subscribers",                   as: "mailerlite_import_subscribers"
        delete "/mailerlite/groups/:id",                    to: "mailerlite#delete",                               as: "mailerlite_delete_group"
        post "/notifications/:id/deliver",                  to: "custom_notification_messages#deliver",            as: "deliver_notification"
        post "/promo_code/import",                          to: "promo_codes#import",                              as: "import_promo_code"

        resources :payments, only: [:index,:update]
        resources :app_versions, except: [:new]
        resources :promo_codes
        resources :categories
        resources :destinations
        resources :custom_notification_messages
        resources :booking_fees, only: [:index,:create]
        resources :referral_incentives, only: [:index,:create]
      end

      scope :payment do
        post "paypal_transaction",  to: "payments#paypal_transaction"
      end

      scope :user do
        get "/notifications",           to: "notifications#index"
        put "/notifications/:id",       to: "notifications#show",                             as: "user_notification"
        get "/notification_count",      to: "notifications#count_users_unseen_notifications", as: "count_unseen_notifications"
        put "/profile_update",          to: "users#update"
      end

      scope :referral do
        post "send_email_invitations",                  to: "referrals#send_invitations",      as: "send_referral_email_invitations"
      end

      scope :instagram do
        get "(/:provider_id)/connect",  to: "instagram#connect",      as: "instagram_connect"
        get "/callback",                to: "instagram#callback",     as: "instagram_callback"
      end

      get "/:role/my_trips",            to: "event#my_trips",       as: "my_trips"
      post "/become_a_trip_organizer",      to: "home#create_form_organiser"
    end

    root "home#index"
    get "profile/:slug/trips",                            to: "users#trips",                   as: "profile_trips"
    get "profile/:slug/reviews",                          to: "users#reviews",                 as: "profile_reviews"
    get "/trips_per_page",                                to: "event#paginated_page"
    get "/paginated_trips",                               to: "users#paginated_trips"
    get "/paginated_reviews",                             to: "users#paginated_reviews"
    get "/trips/:slug",                                   to: "event#page",                    as: "trip_view"
    get "/trips/:slug/joiners",                           to: "event#joiners",                 as: "trip_joiners"
    get "/trips/:slug/checkout/invited_payment_details",  to: "event#invited_payment_details", as: "invited_payment_details"
    get "/who_we_are",                                    to: "home#who_we_are"
    get "/how_it_works",                                  to: "home#how_it_works"
    get "/privacy_policy",                                to: "home#privacy_policy"

app/views/admin/_events.html.erb
<% unless @events.blank? %>
  <table class="payment-table">
    <thead>
      <tr>
        <th></th>
        <th>Trips Name</th>
        <th>Trip Start Date</th>
        <th>Trip End Date</th>
        <th class="center">Featured Trips</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each_with_index do |event, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= link_to event.name, get_event_path(event) %></td>
        <td><%= month_day_year_format event.start_at %></td>
        <td><%= month_day_year_format event.end_at %></td>
        <td class="center"><%= check_box_tag "featured_#{event.id}", 'yes', (true unless event.featured_at.nil?) , onclick: "featureAction(this);"%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <span class="alert label">No found match.</span>
<% end %>

app/views/admin/_joiners.html.erb
<table class="trip-members">
  <thead>
    <th>Joiners</th>
    <th>Payment Mode</th>
    <th>Proof of Payment</th>
    <th>Invited Joiners</th>
    <th>Payment Mode</th>
    <th>Promo Code</th>
    <th>Transaction ID</th>
    <th>Action</th>
  </thead>
  <tbody>
    <% @members.each_with_index do |em, i| %>
      <tr>
        <td><span class="item-no"><%= i + 1 %></span><%= link_to "#{em.member.decorate.full_name}", user_info_path(:user => em.member.id), remote: true %></td>
        <td class="<%= em.payment.made %>"><%= em.payment.made %></td>
        <td class="has-100px-width">
          <% em.payment.payment_photos.each do |p|%>
            <%= link_to image_tag(p.image.url(:thumb)), p.image.url(:xlarge), "data-lightbox" => "image-#{em.member.uid}" %>
          <% end %>
        </td>
        <td class="has-20vw-width">
          <% em.invited_members.each do |member| %>
            <span><%= member.decorate.full_name %></span>
          <% end %>
        </td>
        <td>
          <%= em.payment.mode %>
        </td>
        <td>
          <%= em.payment.promo_code_in_words %>
        </td>
        <td>
          <%= em.payment.transaction_id %>
        </td>
        <td>
          <%= link_to "#", "data-open" => "confirmDelete#{em.id}", title: "Remove Joiner" do |x| %>
            <span class="trash-event ion-trash-b remove-btn"></span>
          <% end %>
          <div class="reveal custom-modal-with-header tiny delete-trip-modal" id="confirmDelete<%= em.id %>" data-reveal>
            <h5>REMOVE</h5>
            <button class="close-button" data-close="" aria-label="Close modal" type="button"></button>
            <p>Are you sure you want to remove this joiner?</p>
            <%= link_to remove_joiner_path(id: em), method: :delete do %>
              <button class="remove-joiner"></span> CONFIRM
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    <div id="userInfoPopUp"></div>
  </tbody>
</table>

app/views/admin/event.html.erb
<% provide(:title, "Admin View Trip") %>
<div class="header">
  <%= link_to "<span class='ion-chevron-left'></span> Back".html_safe, root_path %>
  <h1>Trips</h1>
</div>
<div class="trip-detail-container">
  <strong>Details</strong>
  <table class="trip-detail">
    <tr>
      <td>Organizer:</td>
      <td><%= @event.owner.decorate.full_name %></td>
    </tr>
    <tr>
      <td>Name:</td>
      <td><%= @event.name %></td>
    </tr>
    <tr>
      <td>From:</td>
      <td><%= month_day_year_format @event.start_at.localtime %></td>
    </tr>
    <tr>
      <td>To:</td>
      <td><%= month_day_year_format @event.end_at.localtime %></td>
    </tr>
    <tr class="trip-images">
      <td>Images:</td>
      <% @event.photos.each do |photo| %>
        <td class="image-container"><%= image_tag(photo.image(:xlarge), class: "image") %></td>
      <% end %>
    </tr>
    <tr>
      <td>URL:</td>
      <td colspan="4">
        <span><%= trip_view_url(@event) %></span>
      </td>
    </tr>
    <% if @event.sponsors.present? %>
      <tr class="trip-images">
        <td>Sponsored By:</td>
        <td class="image-container">
          <span><%= image_tag(@event.decorate.brand_sponsor_logo_url, class: "image") %></span>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="actions">
    <%= link_to "EDIT", organizer_trip_edit_path(@event), class: "button primary actions__edit-btn" %>
    <%= button_tag "DELETE", class: "button alert actions__delete-btn", "data-open" => "confirmDelete" %>
  </div>
  <% if @members.blank? %>
    <span class="alert label">No joiners found.</span>
  <% else %>
    <%= render "joiners" %>
  <% end %>
</div>
<div class="reveal custom-modal-with-header tiny delete-trip-modal" id="confirmDelete" data-reveal>
  <h5>DELETE</h5>
  <button class="close-button" data-close="" aria-label="Close modal" type="button"></button>
  <p>Are you sure you want to delete this trip?</p>
  <%= button_to organizer_trips_path(@event), method: :delete, class: "delete-btn", data: { disable_with: "Processing request...." } do %>
    <span class="delete-btn__icon trash-event ion-trash-b"></span> CONFIRM
  <% end %>
</div>

app/views/admin/index.html.erb
<% provide(:title, "Admin Dashboard") %>


<div class="header">
  <h1>TRIPS</h1>
  <%= form_tag admin_path, method: :get, remote: true do %>
    <%= text_field_tag :q, nil, placeholder: "Search", autocomplete: :off , "data-submit-form" => "" %>
  <% end %>
</div>

<div id="eventLists">
  <%= render "events" %>
</div>

<div id="paginator">
  <%= paginate @events, remote: true %>
</div>

app/views/admin/index.js.erb
$("#eventLists").html("<%= j(render('events')) %>");
$("#paginator").html("<%= j(paginate(@events, remote: true)) %>");