config/routes.rb
Rails.application.routes.draw do

  @web = { domain: ["tripkada.com","localhost", "13.250.138.152", "13.229.186.20"] } unless Rails.env.development? || Rails.env.test?
  @api = { subdomain: ["staging-api","api"] } unless Rails.env.development? || Rails.env.test?

  mount Facebook::Messenger::Server, at: 'bot'
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  constraints @api do
    mount API::Base => '/'
  end

  constraints @web do
    authenticate :user do

      scope :profile do
        post "/:slug/reviews",    to: "users#review",                   as: "profile_review"
        get "/:slug/edit",        to: "users#edit",                     as: "profile_edit"
        put "/:slug",             to: "users#update_profile_photos",    as: "profile_update"
        post "/:slug/follow",     to: "users#follow",                   as: "follow_user"
        delete "/:slug/unfollow", to: "users#unfollow",                 as: "unfollow_user"
      end

      scope :trips do
        get "/:slug/checkout",                                to: "event#checkout",                       as: "trip_checkout"
        get "/waitlists/:id/checkout",                        to: "event#waitlist_checkout",              as: "waitlist_checkout"
        get "/:slug/checkout/payment_details",                to: "event#payment_details",                as: "payment_details"
        get "/:slug/checkout/paypal_payment_verification",    to: "payments#paypal_payment_verification", as: "paypal_payment_verification"
        post "/:slug/join",                                   to: "event#join",                           as: "join"
        post "/:slug/join_using_promo_code",                  to: "event#join_using_promo_code",          as: "join_using_promo_code"
        post "/promo_code/validate",                          to: "promo_codes#validate",                 as: "validate_promo_code"
        post "/:slug/join_waitlist",                          to: "event#join_waitlist",                  as: "join_waitlist"
        get  "/:slug/checkout/dragonpay",                     to: "event#dragonpay",                      as: "dragonpay"
      end

      scope :organizer do
        get "/trips/:slug/edit",                      to: "event#edit",               as: "organizer_trip_edit"
        get "/trips/:slug/duplicate",                 to: "event#duplicate",          as: "organizer_trip_duplicate"
        put "/trips/:slug",                           to: "event#update",             as: "organizer_trips"
        delete "/trips/:slug",                        to: "event#destroy"
        get "/create_trip",                           to: "event#new"
        post "/create_trip",                          to: "event#create"
        put "/trip_no_show",                          to: "event#no_show",            as: "trip_no_show"
        scope :manage_trips do
          get "/",                                    to: "manage_trips#index",        as: "manage_trips"
          get "/my_trips",                            to: "manage_trips#trips",        as: "manage_trips_my_trips"
          get "/my_trips/:slug/waitlists",            to: "manage_trips#waitlists",    as: "manage_trips_waitlist"
          put "/my_trips/:slug/cancel",               to: "manage_trips#cancel_trip",  as: "organizer_trip_cancel"
          get "/joiner",                              to: "manage_trips#joiner",       as: "manage_trips_joiner"
          get "/payments",                            to: "manage_trips#payments",     as: "manage_trips_payments"
          get "/funds",                               to: "manage_trips#funds",        as: "manage_trips_funds"
          post "/invite_joiner",                      to: "manage_trips#invite_joiner", as: "organizer_invite_joiner"
          post "/invite_joiner_via_email",            to: "manage_trips#invite_joiner_via_email", as: "organizer_invite_joiner_via_email"
          get "organized_trip_views",                 to: "manage_trips#organized_trip_views"
          get "organized_trip_bookings",              to: "manage_trips#organized_trip_bookings"
          get "monthly_organized_trips",                      to: "manage_trips#monthly_organized_trips"
          get "monthly_organized_trips_booking_count",        to: "manage_trips#monthly_organized_trips_booking_count"

          post 'my_trips/waitlists/update_waitlist',  to: "manage_trips#update_waitlist", as: "update_waitlist"
        end
      end

      scope :admin do
        get "/",                                            to: "admin#index",                                     as: "admin"
        get "/event/:slug",                                 to: "admin#event",                                     as: "get_event"
        get "/users",                                       to: "users#index"
        get "/users/organizer_applicants",                  to: "users#organizer_applicants",                      as: "organizer_applicants"
        get "/users/export_all_organizers",                 to: "users#export_all_organizers",                     as: "export_all_organizers"
        get "/users/export_stats_organizer",                to: "users#export_stats_organizer",                    as: "export_stats_organizer"
        get "/users/cities",                                to: "users#cities"
        get "/users/export",                                to: "users#export",                                    as: "export_users"
        get "/users/segmentations",                         to: "users#segmentations",                             as: "user_segmentations"
        get "/users/export_segmentations",                  to: "users#export_segmentations",                      as: "export_users_segmentation"
        get "/payments/export_all_payments",                to: "payments#export_all_payments",                    as: "export_all_payments"
        get "/users/user_info",                             to: "users#user_info",                                 as: "user_info"
        get "/payments/mark_expired",                       to: "payments#mark_dragonpay_as_expired",              as: "mark_expired_payments"

        delete "/remove_joiner",                            to: "admin#remove_joiner"
        put "/users/:id/update_role",                       to: "users#update_role",                               as: "update_role"
        put "/event/featured",                              to: "admin#make_featured",                             as: "make_featured"
        get "/mailerlite/groups",                           to: "mailerlite#index",                                as: "mailerlite_groups"
        post "/mailerlite/groups",                          to: "mailerlite#create",                               as: "mailerlite_new_group"
        post "/mailerlite/groups/:id/import_subscribers",   to: "mailerlite#import_subscribers",                   as: "mailerlite_import_subscribers"
        delete "/mailerlite/groups/:id",                    to: "mailerlite#delete",                               as: "mailerlite_delete_group"
        post "/notifications/:id/deliver",                  to: "custom_notification_messages#deliver",            as: "deliver_notification"
        post "/promo_code/import",                          to: "promo_codes#import",                              as: "import_promo_code"

        resources :payments, only: [:index,:update]
        resources :app_versions, except: [:new]
        resources :promo_codes
        resources :categories
        resources :destinations
        resources :custom_notification_messages
        resources :booking_fees, only: [:index,:create]
        resources :referral_incentives, only: [:index,:create]
      end

      scope :payment do
        post "paypal_transaction",  to: "payments#paypal_transaction"
      end

      scope :user do
        get "/notifications",           to: "notifications#index"
        put "/notifications/:id",       to: "notifications#show",                             as: "user_notification"
        get "/notification_count",      to: "notifications#count_users_unseen_notifications", as: "count_unseen_notifications"
        put "/profile_update",          to: "users#update"
      end

      scope :referral do
        post "send_email_invitations",                  to: "referrals#send_invitations",      as: "send_referral_email_invitations"
      end

      scope :instagram do
        get "(/:provider_id)/connect",  to: "instagram#connect",      as: "instagram_connect"
        get "/callback",                to: "instagram#callback",     as: "instagram_callback"
      end

      get "/:role/my_trips",            to: "event#my_trips",       as: "my_trips"
      post "/become_a_trip_organizer",      to: "home#create_form_organiser"
    end

    root "home#index"
    get "profile/:slug/trips",                            to: "users#trips",                   as: "profile_trips"
    get "profile/:slug/reviews",                          to: "users#reviews",                 as: "profile_reviews"
    get "/trips_per_page",                                to: "event#paginated_page"
    get "/paginated_trips",                               to: "users#paginated_trips"
    get "/paginated_reviews",                             to: "users#paginated_reviews"
    get "/trips/:slug",                                   to: "event#page",                    as: "trip_view"
    get "/trips/:slug/joiners",                           to: "event#joiners",                 as: "trip_joiners"
    get "/trips/:slug/checkout/invited_payment_details",  to: "event#invited_payment_details", as: "invited_payment_details"
    get "/who_we_are",                                    to: "home#who_we_are"
    get "/how_it_works",                                  to: "home#how_it_works"
    get "/privacy_policy",                                to: "home#privacy_policy"

app/views/shared/_edit_profile_form.html.erb
<%= javascript_include_tag "facebook-optin" %>
<div class="reveal update-details custom-settings-modal-with-header" id="<%= reveal_id %>" data-reveal>
  <header>
    <h5 class="registration">REGISTRATION</h5>
    <p class="fields">
    All fields must be completed for the form to be accepted.
    </p>
  </header>
  <div class="registration-form">
    <%= form_for current_user, url: profile_update_path(current_user.slug), method: :put do |f| %>
      <%= hidden_field_tag(:checkout, reveal_id == 'bookEditDetailModal', id: "proceed_checkout") %>
      <div class="form-field">
        <%= f.text_field :first_name, value: flash[:registration].try(:[], "first_name") || f&.object&.first_name, placeholder: "First Name", required: true %>
      </div>
      <div class="form-field">
        <%= f.text_field :last_name, value: flash[:registration].try(:[], "last_name") || f&.object&.last_name, placeholder: "Last Name", required: true %>
      </div>
      <div class="form-field">
        <%= f.select :gender, User.genders.keys.map{|gender| [gender.titleize, gender]}, {include_blank: "Select a gender"}, {class: "form-control" } %>
      </div>
      <div class="form-field with-icon calendar">
        <%= f.text_field :birthdate, value: date_picker_format(f.object.birthdate) , placeholder: "Birthdate", "data-date-picker" => "" %>
      </div>
      <div class="form-field">
        <%= f.select :country, options_for_select(generate_country_options, "PH") %>
      </div>
      <div class="form-field">
        <%= f.select :city, options_for_select(generate_city_options, "Manila")%>
      </div>
      <div class="form-field">
        <%= f.text_field :mobile, value: flash[:registration].try(:[], "mobile") || f&.object&.mobile, placeholder: "Mobile", required: true %>
      </div>
      <div class="form-field">
        <%= f.text_field :email, placeholder: "Email", value: flash[:registration].try(:[], "email") || f&.object&.email, required: true, type: "email"  %>
      </div>
      <div class="form-field">
        <%= f.text_field :emergency_contact_name, value: flash[:registration].try(:[], "emergency_contact_name") || f&.object&.emergency_contact_number, placeholder: "Emergency Contact Name", required: true  %>
      </div>
      <div class="form-field">
        <%= f.text_field :emergency_contact_number, value: flash[:registration].try(:[], "emergency_contact_number") || f&.object&.emergency_contact_number, placeholder: "Emergency Contact Number", required: true %>
      </div>
      <div class="form-field">
        <%= f.text_field :tell_us_about_yourself, value: flash[:registration].try(:[], "tell_us_about_yourself") || f&.object&.tell_us_about_yourself, placeholder: "Tell us about yourself", required: true %>
      </div>
      <%= check_box_tag "terms_#{reveal_id}", nil, false, class: "custom-circle-check-box without-label" %>
      <%= label_tag "terms_#{reveal_id}", "I agree with the #{ link_to "Terms & Conditions","#"}".html_safe %>
      <% if check_messenger_user_for(f&.object).empty? %>
      <div class="messenger-container">
        <p class="messenger-text">
          Never miss an Announcement or Update! Get your Booking notifications and announcements directly via your <b>FB Messenger!</b>
        </p>
        <div class="messenger-button", style="margin_left = 110px;">
          <div class="fb-send-to-messenger" messenger_app_id="<%= generate_fb_app_id %>"
            page_id="<%= generate_fb_page_id %>"
            data-ref="registration_form_ref=page_id:<%= generate_fb_page_id %>/user_id:<%=f.object.id%>"
            color="blue" size="large">
          </div>
        </div>
      </div>
      <% end %>
      <p class="submit">
      <%= f.submit "SUBMIT" %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/_fb_customer_chat_plugin.html.erb
<div class="fb-livechat">
  <div class="ctrlq fb-overlay"></div>
  <div class="fb-widget">
    <div class="ctrlq fb-close"></div>
    <div class="fb-page" data-href="https://www.facebook.com/JoinTripkada/" data-tabs="messages" data-width="360" data-height="400" data-small-header="true" data-hide-cover="true" data-show-facepile="false">
      <blockquote cite="https://www.facebook.com/JoinTripkada/" class="fb-xfbml-parse-ignore"> </blockquote>
    </div>
    <div class="fb-credit"> 
      <a href="https://www.tripkada.com" target="_blank">Tripkada Facebook Chat Widget</a>
    </div>
    <div id="fb-root"></div>
  </div>
  <a href="https://www.messenger.com/t/JoinTripkada" title="Send us a message on Facebook" class="ctrlq fb-button"><span class="fb-button-text">Chat with us</span></a> 
</div>

app/views/shared/_fb_customer_chat_plugin.mobile.erb
<div class="fb-livechat">
  <div class="ctrlq fb-overlay"></div>
  <div class="fb-widget fb-widget--mobile">
    <div class="ctrlq fb-close"></div>
    <div class="fb-page" data-href="https://www.facebook.com/JoinTripkada/" data-tabs="messages" data-width="360" data-height="400" data-small-header="true" data-hide-cover="true" data-show-facepile="false">
      <blockquote cite="https://www.facebook.com/JoinTripkada/" class="fb-xfbml-parse-ignore"> </blockquote>
    </div>
    <div class="fb-credit"> 
      <a href="https://www.tripkada.com" target="_blank">Tripkada Facebook Chat Widget</a>
    </div>
    <div id="fb-root"></div>
  </div>
  <a href="https://www.messenger.com/t/JoinTripkada" title="Send us a message on Facebook" class="ctrlq fb-button"><span class="fb-button-text">Chat with us</span></a> 
</div>

app/views/shared/_fb_pixel.html.erb
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '<%= ENV['FB_PIXEL_ID'] %>'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=<%= ENV['FB_PIXEL_ID'] %>&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

app/views/shared/_fb_pixel.mobile.erb
<!-- Facebook Pixel Code -->
<script>
  !function (f, b, e, v, n, t, s) {
    if (f.fbq)
      return;
    n = f.fbq = function () {
      n.callMethod
        ? n.callMethod.apply(n, arguments)
        : n.queue.push(arguments)
    };
    if (!f._fbq)
      f._fbq = n;
    n.push = n;
    n.loaded = !0;
    n.version = '2.0';
    n.queue = [];
    t = b.createElement(e);
    t.async = !0;
    t.src = v;
    s = b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t, s)
  }(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '<%= ENV[' FB_PIXEL_ID '] %>'); // Insert your pixel ID here.
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<%= ENV['FB_PIXEL_ID'] %>&ev=PageView&noscript=1"/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

app/views/shared/_flash.mobile.erb
<script type="text/javascript" charset="utf-8">
  window.onload = function () {
    <% if flash[:notice].present? %>
      popupNotification("success", '<%= flash[:notice] %>');
    <% end %>
    <% if flash[:alert].present? %>
      popupNotification("alert", '<%= flash[:alert] %>');
    <% end %>
  }
</script>

app/views/shared/_footer.mobile.erb
<footer class="main-footer">
  <div>
    <%=render_navigation(context: :footer, expand_all: true) %>
  </div>
  <p class="explore">Explore wih us through:</p>
  <div class="social-links-grp">
    <ul class="links">
      <li><%= link_to icon("facebook"),  "https://www.facebook.com/JoinTripkada/" %></li>
      <li><%= link_to icon("twitter"),  "#" %></li>
      <li><%= link_to icon("instagram"),  "https://www.instagram.com/tripkada/" %></li>
    </ul>
  </div>
  <p class="copy"><%= icon "copyright" %>
    2016 Tripkada, Part of FlipTrip Travels, Inc.</p>
</footer>

app/views/shared/_loader.html.erb
<div class="loader-wrapper">
  <div class="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>

app/views/shared/_loader.mobile.erb
<div class="loader-wrapper">
  <div class="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>

app/views/shared/_nav.html.erb
<nav class="top-nav">
  <div class="logo-col">
    <%=tabs_tag do |tab| %>
    <%=tab.home "#{image_tag('tripkada-logo-new-2.png',class: 'logo')}".html_safe, root_path %>
    <% end %>
  </div>
  <div class="header-link-col">
    <%=render_navigation(context: :event, expand_all: true) %>
    <% if user_signed_in? %>
    <%= render partial: 'shared/edit_profile_form', locals: { reveal_id: 'editDetailModal' } %>
    <%= render partial: 'shared/referral_modal' %>
    <% end %>
  </div>
</nav>
<div class='reveal tiny tripkada-modal tripkada-login' id='sign-upModal' data-reveal>
  <%= generate_login_signup_link_home(label: "SIGN UP") %>
</div>
<div class='reveal tiny tripkada-modal tripkada-login' id='loginModal' data-reveal>
  <%= generate_login_signup_link_home(label: "LOGIN") %>
</div>

app/views/shared/_nav.mobile.erb
<nav class="top-nav">
  <div class="logo-col">
    <%=tabs_tag do |tab| %>
    <%=tab.home "#{image_tag('tripkada-logo-new-2.png', class: 'logo')}".html_safe, root_path %>
    <% end %>
  </div>
  <div class="wrapper-nav">
    <% if user_signed_in? %>
    <div class="title-bar collapsible-container" data-responsive-toggle="nav-content" data-hide-for="xxlarge">
      <button class="menu-icon toggle-btn" type="button" data-toggle data-open="content-modal"></button>
    </div>
    <ul class="dropdown menu menu-mobile" data-dropdown-menu>
      <li class="notification-alert <%= 'hidden' if users_notification_empty? %>" id="notification-count">
        <%= link_to content_tag(:span, users_notification_count_string), notifications_path %>
      </li>
      <li class="dropdown-arrow">
        <a href="#" class="user-logout logged-user">
          <div style="background-image:url(<%= current_user.decorate.avatar_url(:thumb) %>)"></div>
        </a>
        <ul class="menu vertical hide-mobile">
          <li><%= link_to "Notifications", notifications_path %></li>
          <li><%=link_to "My Profile", profile_path(current_user.slug)%></li>
          <li>
            <%=link_to "Settings", "#", "data-open"=> "editDetailModal" %>
            <%= render partial: 'shared/edit_profile_form', locals: { reveal_id: 'editDetailModal' } %>
          </li>
          <li>
            <%=link_to "My Credits", "#", "data-open"=> "referralModal" %>
            <%= render partial: 'shared/referral_modal' %>
          </li>
          <li>
            <%=link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </li>
    </ul>
  <% else %>
    <%= generate_download_button %>
    <div class="title-bar collapsible-container" data-responsive-toggle="nav-content" data-hide-for="xxlarge">
      <button class="menu-icon toggle-btn" type="button" data-toggle data-open="content-modal"></button>
    </div>
    <% end %>
  </div>
  <div class="content-modal reveal" id="content-modal" data-reveal>
    <button class="close-button" data-close aria-label="Close reveal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
    <ul id='content-modal'>
      <%=render_navigation(context: :event, expand_all: true) %>
    </ul>
  </div>
  <div class="reveal tiny login-modal tripkada-login" id="loginModal" data-reveal>
    <%= generate_login_signup_link_home(label: "LOGIN") %>
  </div>
  <div class="reveal tiny login-modal tripkada-login" id="sign-upModal" data-reveal>
    <%= generate_login_signup_link_home(label: "SIGN UP") %>
  </div>
</nav>

app/views/shared/_pagination_loader.html.erb
<div id="pagination-loader" class="pagination-event-loading"><%= image_tag("tripkada-loader.gif")%></div>

app/views/shared/_pagination_loader.mobile.erb
<div id="pagination-loader" class="pagination-event-loading"><%= image_tag("tripkada-loader.gif")%></div>

app/views/shared/_referral_modal.html.erb
<div class="reveal referral-modal-with-header" id="referralModal" data-reveal>
  <header>
    <button class="close-button" data-close aria-label="Close modal" type="button"></button>
    <div class="title">Free Trips</div>
    <hr>
    <ul class="tabs" data-active-collapse="true" data-tabs id="collapsing-tabs">
      <li class="tabs-title is-active">
        <a href="#referral-modal-tab-invite" aria-selected="true">Invite</a>
      </li>
      <li class="tabs-title">
        <a href="#referral-modal-tab-credits">My Travel Credits</a>
      </li>
    </ul>
    <div class="tabs-content" data-tabs-content="collapsing-tabs">
      <div class="tabs-panel is-active" id="referral-modal-tab-invite">
        <div class="referral-image">
          <%= image_tag 'referral-invite.png' %>
          <div class="referral-image-label">
            <p class="referral-image-label__text">Share your</p>
            <p class="referral-image-label__text">love of</p>
            <p class="referral-image-label__text referral-image-label__text--big">Travel</p>
          </div>
        </div>
        <div class="invite-container">
          <p class="small">When a friend joins a trip on Tripkada, you earn
            <b>PHP100</b>
            in travel credits for your next trip!</p>
          <label for="">
            <b>Enter Email Addresses</b>
          </label>
          <%= form_tag send_referral_email_invitations_path do %>
          <%= text_field_tag 'emails', nil, placeholder: "Emails", id: "email-tags" %>
          <div class="button-container">
            <%= submit_tag "SEND INVITES" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tabs-panel" id="referral-modal-tab-credits">
        <%= image_tag 'referral-credits.png', class: 'credits' %>
        <div class="button-container">
          <p class="content">
            You have
            <span class="bold"><%= currency_format(credit_promo_code_available_credits, "P") %></span>
            travel credits
          </p>
          <p class="content">
            Your promo code is:
            <span class="bold"><%= credit_code %></span>
          </p>
        </div>
      </div>
    </div>
  </header>
</div>