config/routes.rb
          get "/my_trips",                            to: "manage_trips#trips",        as: "manage_trips_my_trips"
          get "/my_trips/:slug/waitlists",            to: "manage_trips#waitlists",    as: "manage_trips_waitlist"
          put "/my_trips/:slug/cancel",               to: "manage_trips#cancel_trip",  as: "organizer_trip_cancel"
          get "/joiner",                              to: "manage_trips#joiner",       as: "manage_trips_joiner"
          get "/payments",                            to: "manage_trips#payments",     as: "manage_trips_payments"
          get "/funds",                               to: "manage_trips#funds",        as: "manage_trips_funds"
          post "/invite_joiner",                      to: "manage_trips#invite_joiner", as: "organizer_invite_joiner"
          post "/invite_joiner_via_email",            to: "manage_trips#invite_joiner_via_email", as: "organizer_invite_joiner_via_email"
          get "organized_trip_views",                 to: "manage_trips#organized_trip_views"
          get "organized_trip_bookings",              to: "manage_trips#organized_trip_bookings"
          get "monthly_organized_trips",                      to: "manage_trips#monthly_organized_trips"
          get "monthly_organized_trips_booking_count",        to: "manage_trips#monthly_organized_trips_booking_count"

          post 'my_trips/waitlists/update_waitlist',  to: "manage_trips#update_waitlist", as: "update_waitlist"
        end
      end

      scope :admin do
        get "/",                                            to: "admin#index",                                     as: "admin"
        get "/event/:slug",                                 to: "admin#event",                                     as: "get_event"
        get "/users",                                       to: "users#index"
        get "/users/organizer_applicants",                  to: "users#organizer_applicants",                      as: "organizer_applicants"
        get "/users/export_all_organizers",                 to: "users#export_all_organizers",                     as: "export_all_organizers"
        get "/users/export_stats_organizer",                to: "users#export_stats_organizer",                    as: "export_stats_organizer"
        get "/users/cities",                                to: "users#cities"
        get "/users/export",                                to: "users#export",                                    as: "export_users"
        get "/users/segmentations",                         to: "users#segmentations",                             as: "user_segmentations"
        get "/users/export_segmentations",                  to: "users#export_segmentations",                      as: "export_users_segmentation"
        get "/payments/export_all_payments",                to: "payments#export_all_payments",                    as: "export_all_payments"
        get "/users/user_info",                             to: "users#user_info",                                 as: "user_info"
        get "/payments/mark_expired",                       to: "payments#mark_dragonpay_as_expired",              as: "mark_expired_payments"

        delete "/remove_joiner",                            to: "admin#remove_joiner"
        put "/users/:id/update_role",                       to: "users#update_role",                               as: "update_role"
        put "/event/featured",                              to: "admin#make_featured",                             as: "make_featured"
        get "/mailerlite/groups",                           to: "mailerlite#index",                                as: "mailerlite_groups"
        post "/mailerlite/groups",                          to: "mailerlite#create",                               as: "mailerlite_new_group"
        post "/mailerlite/groups/:id/import_subscribers",   to: "mailerlite#import_subscribers",                   as: "mailerlite_import_subscribers"
        delete "/mailerlite/groups/:id",                    to: "mailerlite#delete",                               as: "mailerlite_delete_group"
        post "/notifications/:id/deliver",                  to: "custom_notification_messages#deliver",            as: "deliver_notification"
        post "/promo_code/import",                          to: "promo_codes#import",                              as: "import_promo_code"

        resources :payments, only: [:index,:update]
        resources :app_versions, except: [:new]
        resources :promo_codes
        resources :categories
        resources :destinations
        resources :custom_notification_messages
        resources :booking_fees, only: [:index,:create]
        resources :referral_incentives, only: [:index,:create]
      end

      scope :payment do
        post "paypal_transaction",  to: "payments#paypal_transaction"
      end

      scope :user do
        get "/notifications",           to: "notifications#index"
        put "/notifications/:id",       to: "notifications#show",                             as: "user_notification"
        get "/notification_count",      to: "notifications#count_users_unseen_notifications", as: "count_unseen_notifications"
        put "/profile_update",          to: "users#update"
      end

      scope :referral do
        post "send_email_invitations",                  to: "referrals#send_invitations",      as: "send_referral_email_invitations"
      end

      scope :instagram do
        get "(/:provider_id)/connect",  to: "instagram#connect",      as: "instagram_connect"
        get "/callback",                to: "instagram#callback",     as: "instagram_callback"
      end

      get "/:role/my_trips",            to: "event#my_trips",       as: "my_trips"
      post "/become_a_trip_organizer",      to: "home#create_form_organiser"
    end

    root "home#index"
    get "profile/:slug/trips",                            to: "users#trips",                   as: "profile_trips"
    get "profile/:slug/reviews",                          to: "users#reviews",                 as: "profile_reviews"
    get "/trips_per_page",                                to: "event#paginated_page"
    get "/paginated_trips",                               to: "users#paginated_trips"
    get "/paginated_reviews",                             to: "users#paginated_reviews"
    get "/trips/:slug",                                   to: "event#page",                    as: "trip_view"
    get "/trips/:slug/joiners",                           to: "event#joiners",                 as: "trip_joiners"
    get "/trips/:slug/checkout/invited_payment_details",  to: "event#invited_payment_details", as: "invited_payment_details"
    get "/who_we_are",                                    to: "home#who_we_are"
    get "/how_it_works",                                  to: "home#how_it_works"
    get "/privacy_policy",                                to: "home#privacy_policy"
    get "/collaborate_on_project",                        to: "home#collaborate"
    post "/sign_me_up",                                   to: "home#sign_me_up"
    get "/trips",                                         to: "event#index"
    get "/users/sign_in/organizer",                       to: "home#sign_in_as_organizer",     as: "organizer_sign_in"
    get "/apply_for_a_job",                               to: "home#apply_for_a_job"
    get "/trip_requests",                                 to: "home#requests"
    post "/trip_requests",                                to: "home#create_requests"
    get "/questions",                                     to: "home#questions"
    post "/questions",                                    to: "home#create_questions"
    get "/tagcash_callback",                              to: "home#tagcash_callback"
    get "/profile/:slug",                                 to: "users#show",                    as: "profile"
    match "/404",                                         to: "custom_errors#page_not_found", via: :all
    get 'users/uid',                                      to: "users#current_user_uid",        as: "users_uid"
    get 'organizer/landing_page',                         to: "organizer#index",               as: "organizer_landing_page"
    get "/be_a_trip_organizer",                           to: "home#apply_as_organiser",       as: "be_a_trip_organizer"

    get "/messenger_webview/set_profile",                                to: "messenger_webview#set_profile"
    get "/messenger_webview/unset_profile",                              to: "messenger_webview#unset_profile"
    get "/messenger_webview/subscribe",                                  to: "messenger_webview#subscribe"
    get "/messenger_webview/unsubscribe",                                to: "messenger_webview#unsubscribe"
    get "/messenger_webview/specific_date_trips/:fbuser_obj_id",         to: "messenger_webview#specific_date_trips"
    get "/messenger_webview/destination_based_trips/:fbuser_obj_id",     to: "messenger_webview#destination_based_trips"
    get "/messenger_webview/activity_based_trips/:fbuser_obj_id",        to: "messenger_webview#activity_based_trips"
    get "/messenger_webview/event_filters/:fbuser_obj_id",               to: "messenger_webview#event_filters"
    get "/messenger_webview/filtered_events",                            to: "messenger_webview#filtered_events"
    get "/messenger_webview/fill_up_form/:fbuser_obj_id",                to: "messenger_webview#fill_up_form"
    get "/messenger_webview/checkout_notif/:membership_id/:fbuser_obj_id", to: "messenger_webview#checkout_notif"
    get "/invitee/validate_email/"                                       , to: "event#validate_invitee_email"
    scope :payment do
      get  "/dragonpay/callback", to: "payments#dragonpay_callback"
      post  "/dragonpay/postback", to: "payments#dragonpay_postback"
    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UsersHelper
  include DeviceValidator
  before_action :ensure_organizer_or_joiner, if: :user_signed_in?
  before_action :ensure_valid_email, only: [:create_requests, :create_questions, :create_form_organiser]
  def index
    upcoming_events = Event.not_deleted.upcoming
    @user = User.new
    @featured_events = upcoming_events.featured.order_by_start.limit(3).decorate
    @upcoming_events = upcoming_events.order_by_start.limit(3).decorate
    @this_months_events = upcoming_events.this_month.order_by_start.limit(3).decorate
    @destinations = Destination.all
    @categories = Category.all
  end

  def how_it_works
  end

  def privacy_policy
  end

  def who_we_are
  end

  def collaborate
  end

  def apply_as_organiser
  end

  def apply_for_a_job
  end

  def requests
  end

  def create_requests
    Notifications::EmailWorker.perform_async(params, "trip_request")
    redirect_to trip_requests_path, notice: "Successfully sent!."
  end

  def questions
  end

  def create_questions
    params[:registration_platform] = check_device_platform(
      user_agent: request.user_agent,
      type: "controller"
    )
    Notifications::EmailWorker.perform_async(params, "question")
    redirect_to questions_path, notice: "Successfully sent!."
  end

  def sign_in_as_organizer
  end

  def sign_in_as_joiner
  end

  def create_form_organiser
    current_user.apply_as_organizer!
    params[:organizer_application_platform] = check_device_platform(
      user_agent: request.user_agent,
      type: "controller"
    )
    Notifications::EmailWorker.perform_async(params, "apply_as_organiser")
    redirect_to organizer_landing_page_path,
    notice: "Application Request Successfully sent!."
  end

  def sign_me_up
    @user = User.new(sign_me_up_params)
    @user.password = 'password'
    Notifications::EmailWorker.perform_async(@user, "sign_me_up_email")
    redirect_to root_url, notice: "Successfully sent!."
  end

  def authenticated_redirect
    flash[flash.first[0].to_sym] = flash.first[1] if flash.present?
    redirect_to dynamic_path_for(current_user)
  end

  def tagcash_callback
    handler = TagcashHandler.new(params[:code], params[:state]).get_access_token
    path = if event = Event.find_by(slug: handler.response[:event])
             payment_details_path(event, code: handler.response[:promo_code], mode: "tagcash")
           else
             root_path
           end

    if handler.response[:type]
      redirect_to path, notice: handler.response[:details]
    else
      redirect_to root_path, alert: handler.response[:details]
    end
  end

  private
  def sign_me_up_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

  def ensure_valid_email
    valid = valid_email?(email: params[:email])
    redirect_to :back, alert: "Please use a valid email." unless valid
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def generate_title(type)
    case type
      when "featured" then "FEATURED TRIPS"
      when "upcoming" then "UPCOMING TRIPS"
      else
        "TRIPS THIS MONTH"
    end
  end

  def generate_button_for(type)
    case type
      when "featured"
        link_to "SEE ALL FEATURED TRIPS", trips_path(featured: true), class: 'button'
      when "upcoming"
        link_to "SEE ALL UPCOMING TRIPS", trips_path, class: 'button'
      else
        link_to "SEE ALL TRIPS THIS MONTH", trips_path(start_month: month_year_format(DateTime.current), end_month: month_year_format(DateTime.current)), class: 'button'
    end
  end

  def generate_organizer_application_form_submit_btn
    if user_signed_in?
      button_tag "SUBMIT"
    else
      content_tag :button, "SUBMIT", type:"button", data: { open: "loginModal" }
    end
  end

  def generate_user_info(field)
    current_user.try(field) || params[field]
  end
end

app/views/home/_trips.mobile.erb
<div class="trips-container">
  <div class="title-container">
    <p><%= generate_title(type) %></p>
  </div>
  <% if events.blank? %>
    <div class="event-container trips">
      No trips found.
    </div>
  <% end %>
  <div class="row event-container trips-page-mobile">
    <% events.each do |event| %>
      <div class="small-12 columns" >
        <%= link_to trip_view_path(event) do %>
          <div class="event-bg-container-front" style="background-image:url(<%= event.cover_photo_url(:large) %>)">
            <%= image_tag "gradient.png", class: "mask" %>
            <div class="details-wrapper">
              <p class="departure-date"><%= event.travel_dates.upcase %></p>
              <div class="trip-title-container">
                <h1 class="title"><%= event.name %></h1>
              </div>
              <%= brand_sponsor_logo(event) %>
            </div>
          </div>
          <%= render 'event/event_details', event: event %>
        <% end %>
      </div>
    <% end %>
    <p>
      <%= generate_button_for(type) unless events.blank? %>
    </p>
  </div>
</div>

app/views/home/apply_as_organiser.html.erb
<% provide(:title, "Be a trip organizer") %>

<div class="organiser-form-container">
  <div class="row">
    <h1>Be a trip organizer</h1>
    <p><span>Trip</span><span>kada</span> provides a curated platform for trip organizers, whether from travel agencies, tour operators, and yes, informal and independent joining trip organizers, who want to open their trips to joiners</p>
    <p>We're about building our community of travelers, and if you think you have what it takes to join our pool of Trip Organizers, and post your own trips on Tripkada, please do fill up the form below. We'll review it, and contact you as soon as we can.</p>
    <%= form_tag become_a_trip_organizer_path, class: "organiser-form" do %>
     <div class="medium-6 columns">
      <%= text_field_tag :first_name, nil, placeholder: "Firstname", value: current_user&.first_name, required: true %>
     </div>
     <div class="medium-6 columns">
      <%= text_field_tag :last_name, nil, placeholder: "Lastname", value: current_user&.last_name, required: true %>
     </div>
     <div class="medium-12 columns">
      <%= text_field_tag :mobile, nil, placeholder: "Cellphone Number", value: current_user&.mobile, required: true %>
      <%= email_field_tag :email, nil, placeholder: "E-mail Address", value: current_user&.email, required: true %>
      <%= text_field_tag :fb_page, nil, placeholder: "Facebook Page, If any" %>
      <%= text_field_tag :website, nil, placeholder: "Website, If any" %>
      <%= text_area_tag :destination, nil,placeholder: "Destinations covered:", rows: 3 %>
      <%= text_area_tag :itinerary, nil,placeholder: "Sample trip itinerary:", rows: 3 %>
      <%= generate_organizer_application_form_submit_btn %>
     </div>
  <% end %>
  </div>
</div>
<script>
  window.onload = function () {
    <% unless user_signed_in? %>
      $('#loginModal').foundation('toggle')
    <% end %>
  }
</script>

app/views/home/apply_for_a_job.html.erb
<% provide(:title, "Apply for a job") %>

<div class="apply-for-a-job-container">
  <div class="row">
    <h1>Apply for a job</h1>
    <p>Full-time, part-time, intern, volunteer. Sometimes. we don't even know what we're looking for. Tell us what you want to do with and for us, and what do you think you can tangibly do to help us reach our vision of changing the face of travel here in the Philippines and the world.</p>
    <p>Send your applications to <a href="mailto:join@tripkada.com" class="mail">join@tripkada.com</a>, with your answer and your updated resume, and we'll do our best to get in touch with you.</p>
    <p>Please understand that we get a lot of applications, so if we don't find that we're not meant to be, you won't get a response. It's not you, it's. It's hard to respond to everyone. :)</p>
  </div>
</div>

app/views/home/apply_for_a_job.mobile.erb
<% provide(:title, "Apply for a job") %>

<div class="apply-for-a-job-container">
  <div class="row">
    <h1>Apply for a job</h1>
    <p>Full-time, part-time, intern, volunteer. Sometimes. we don't even know what we're looking for. Tell us what you want to do with and for us, and what do you think you can tangibly do to help us reach our vision of changing the face of travel here in the Philippines and the world.</p>
    <p>Send your applications to <a href="mailto:join@tripkada.com" class="mail">join@tripkada.com</a>, with your answer and your updated resume, and we'll do our best to get in touch with you.</p>
    <p>Please understand that we get a lot of applications, so if we don't find that we're not meant to be, you won't get a response. It's not you, it's. It's hard to respond to everyone. :)</p>
  </div>
</div>

app/views/home/how_it_works.html.erb
<% provide(:title, "How it works") %>

<div class="how-it-works-container">
  <div class="row">
    <h1>How it works</h1>
    <p>Tripkada is made possible by it's community of travelers who organize trips independently. Trip organizers do not work for tripkada, unless specified. They are curated and given special access to your organizer app, trainings and events that we hope will help them to provide great experiences for their joiners</p>
   </div>
   <div class="flex-display">
    <div class="img-column">
      <%= image_tag "phone.png" %>
    </div>
    <div class="text-column">
      <p>Log into Tripkada and find a stream of available trips for the weekend. Check what fits what you feel like doing, whether it's to hike up a mountain, surf at the beach, or just plain bum somewhere with a great view.</p>
    </div>
   </div>
   <div class="flex-display">
    <div class="text-column">
      <p>Pick your trip, and join it by paying the downpayment of PHP 500-800 through the different payment options. simple choose what's convenient for you</p>
    </div>
    <div class="img-column">
      <%= image_tag "phone.png" %>
    </div>
   </div>
   <div class="flex-display">
    <div class="img-column">
      <%= image_tag "phone.png" %>
    </div>
    <div class="text-column">
      <p>Wait for your confimation and reminders, and get ready for your next epic weekend!</p>
    </div>
  </div>
</div>

app/views/home/how_it_works.mobile.erb
<% provide(:title, "How it works") %>

<div class="how-it-works-container">
  <div class="row">
    <h1>How it works</h1>
    <p>Tripkada is made possible by it's community of travelers who organize trips independently. Trip organizers do not work for tripkada, unless specified. They are curated and given special access to your organizer app, trainings and events that we hope will help them to provide great experiences for their joiners</p>
   </div>
   <div class="flex-display">
    <div class="img-column">
      <%= image_tag "phone.png" %>
    </div>
    <div class="text-column">
      <p>Log into Tripkada and find a stream of available trips for the weekend. Check what fits what you feel like doing, whether it's to hike up a mountain, surf at the beach, or just plain bum somewhere with a great view.</p>
    </div>
   </div>
   <div class="flex-display">
    <div class="img-column">
      <%= image_tag "phone.png" %>
    </div>
    <div class="text-column">
      <p>Pick your trip, and join it by paying the downpayment of PHP 500-800 through the different payment options. simple choose what's convenient for you</p>
    </div>
   </div>
   <div class="flex-display">
    <div class="img-column">
      <%= image_tag "phone.png" %>
    </div>
    <div class="text-column">
      <p>Wait for your confimation and reminders, and get ready for your next epic weekend!</p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<% content_for :opengraphs do %>
  <meta name="google-site-verification" content="OXwjFNmPp9GxJ36XQVP2nO49aX7IpPUQai1Xb12k39U" />
  <meta property="fb:app_id" content="<%= ENV['FB_APP_ID'] %>" />
  <meta property="og:title" content="Tripkada" />
  <meta property="og:description" content="Join trips planned by travelers like you.Learn more Now!." />
  <meta name="description" content="Join trips planned by travelers like you.Learn more Now!." />
  <meta property="og:image" content="<%= asset_url "tripkada-og-logo.png"  %>" />
<% end%>
<div class="home-container">
  <div class="header-grp">
    <h1>Join Trips</h1>
    <h1>PLANNED BY</h1>
    <h1>TRAVELERS</h1>
    <h1>like you</h1>
  </div>
  <div class="bottom-grp">
    <div class="search-container">
      <%= form_tag trips_path, method: :get do %>
        <div class="form-field">
          <%= select_tag :destination_id, options_from_collection_for_select(@destinations, "id", "name"), prompt: "Where do you want to go?" %>
        </div>
        <div class="form-field">
          <%= select_tag :category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: "Activities" %>
        </div>
        <div class="form-field">
          <%= submit_tag "Search", name: nil, class: "search-button" %>
        </div>
      <% end %>
    </div>
    <ul class="downloads">
      <li>
        <span>DOWNLOAD THE APP</span>
        <%= link_to image_tag("store_google_white.png"), "https://play.google.com/store/apps/details?id=ph.fliptrip.tripkada.joiner", target: "_blank" %>
      </li>
      <li>
        <span>DOWNLOAD THE APP</span>
        <%= link_to image_tag("Appstore_white.png"), "https://itunes.apple.com/ph/app/tripkada-trip-pooling-app/id1333012684?mt=8", target: "_blank" %>
      </li>
    </ul>
  </div>
</div>
<div class="event-wrapper main">
  <%= render "trips", events: @featured_events, type: "featured" %>
  <%= render "trips", events: @upcoming_events, type: "upcoming" %>
  <%= render "trips", events: @this_months_events, type: "trips_this_month" %>
</div>

<%= content_for :page_javascripts do %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

     ga('create', 'UA-82268743-1', 'auto');
     ga('send', 'pageview');

    <% if current_user.present? && has_completed_data_of(current_user) %>
    $(document).ready(function(){$('#editDetailModal').foundation('open')});
    <% end %>
  </script>
<% end %>

app/views/home/index.mobile.erb
<% provide(:title, "Home") %>

<% content_for :opengraphs do %>
  <meta name="google-site-verification" content="OXwjFNmPp9GxJ36XQVP2nO49aX7IpPUQai1Xb12k39U" />
  <meta property="fb:app_id" content="<%= ENV['FB_APP_ID'] %>" />
  <meta property="og:title" content="Tripkada" />
  <meta property="og:description" content="Join trips planned by travelers like you.Learn more Now!." />
  <meta name="description" content="Join trips planned by travelers like you.Learn more Now!." />
  <meta property="og:image" content="<%= asset_url "tripkada-og-logo.png"  %>" />
<% end%>

<div class="home-container">

  <div class="header-grp">
    <h1>Join Trips</h1>
    <h1>PLANNED BY</h1>
    <h1>TRAVELERS</h1>
    <h1>like you</h1>
  </div>

  <div class="bottom-grp">
    <div class="search-container">
      <%= form_tag trips_path, method: :get do %>
        <div class="form-field">
          <%= select_tag :destination_id, options_from_collection_for_select(@destinations, "id", "name"), prompt: "Where do you want to go?" %>
        </div>
        <div class="form-field">
          <%= select_tag :category_id, options_from_collection_for_select(@categories, "id", "name"), prompt: "Activities" %>
        </div>
        <div class="form-field">
          <%= submit_tag "Search", class: "search-button" %>
        </div>
      <% end %>
    </div>
    <ul class="downloads">
      <li>
        <span>DOWNLOAD THE APP</span>
        <%= link_to image_tag("store_google_white.png"), "https://play.google.com/store/apps/details?id=ph.fliptrip.tripkada.joiner", target: "_blank" %></li>
      <li>
        <span>DOWNLOAD THE APP</span>
        <%= link_to image_tag("Appstore_white.png"),  "https://itunes.apple.com/ph/app/tripkada-trip-pooling-app/id1333012684?mt=8", target: "_blank"  %>
      </li>
    </ul>
  </div>

</div>
<%= render "trips", events: @featured_events, type: "featured" %>
<%= render "trips", events: @upcoming_events, type: "upcoming" %>
<%= render "trips", events: @this_months_events, type: "trips_this_month" %>
<%= content_for :page_javascripts do %>
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-82268743-1', 'auto');
 ga('send', 'pageview');

</script>
<% end %>

app/views/home/questions.html.erb
<% provide(:title, "Questions") %>

<div class="questions-form-container">
  <div class="row">
    <h1>Questions</h1>
    <p class="center">Got something on your mind? We'd love to chat! How can we help you?</p>
    <%= form_tag questions_path, method: :post, class: "organiser-form" do %>
     <div class="medium-6 columns">
      <%= text_field_tag :fname, nil, placeholder: "Firstname" %>
     </div>
     <div class="medium-6 columns">
      <%= text_field_tag :lname, nil, placeholder: "Lastname" %>
     </div>
     <div class="medium-12 columns">
      <%= text_field_tag :number, nil, placeholder: "Cellphone Number" %>
      <%= text_field_tag :email, nil, placeholder: "E-mail Address" %>
      <%= text_area_tag :message, nil, placeholder: "Message", rows: 3 %>
      <%= button_tag "SUBMIT" %>
     </div>
  <% end %>
  </div>
</div>

app/views/home/questions.mobile.erb
<% provide(:title, "Questions") %>

<div class="questions-form-container">
  <div class="row">
    <h1>Questions</h1>
    <p class="center">Got something on your mind? We'd love to chat! How can we help you?</p>
    <%= form_tag questions_path, method: :post, class: "organiser-form" do %>
     <div class="medium-6 columns">
      <%= text_field_tag :fname, nil, placeholder: "Firstname" %>
     </div>
     <div class="medium-6 columns">
      <%= text_field_tag :lname, nil, placeholder: "Lastname" %>
     </div>
     <div class="medium-12 columns">
      <%= text_field_tag :number, nil, placeholder: "Cellphone Number" %>
      <%= text_field_tag :email, nil, placeholder: "E-mail Address" %>
      <%= text_area_tag :message, nil, placeholder: "Message", rows: 3 %>
      <%= button_tag "SUBMIT" %>
     </div>
  <% end %>
  </div>
</div>

app/views/home/requests.html.erb
<% provide(:title, "Trip requests") %>

<div class="trip-requests-form-container">
  <div class="row">
    <h1>Trip requests</h1>
    <p>Maybe you can't find what you're looking for, or you want something different or private. Fear not! Our travel experts are here to your rescue. Just let us know what you have in mind. how long you want to travel for, and how much you're willing to spend. We'll take care of it, and do our best to make sure you have the best experience possible.</p>
    <%= form_tag trip_requests_path, method: :post, class: "organiser-form" do %>
     <div class="medium-6 columns">
      <%= text_field_tag :fname, generate_user_info(:first_name), placeholder: "Firstname" %>
     </div>
     <div class="medium-6 columns">
      <%= text_field_tag :lname, generate_user_info(:last_name), placeholder: "Lastname" %>
     </div>
     <div class="medium-6 columns">
      <%= text_field_tag :number, generate_user_info(:mobile), placeholder: "Cellphone Number" %>
     </div>
     <div class="medium-6 columns">
      <%= email_field_tag :email, generate_user_info(:email), placeholder: "E-mail Address",type: "email", required: true%>
    </div>
     <div class="medium-12 columns">
      <%= text_area_tag :itinerary, params[:event], placeholder: "Not sure where? Tell us what you want to do", rows: 3 %>
      <%= text_field_tag :start_end_at, nil, placeholder: "When would you like to go? Departing, Returning" %>
      <%= text_area_tag :budget, nil, placeholder: "How much are you willing to spend on your accomodation?", rows: 3 %>
      <%= text_area_tag :pax, nil, placeholder: "How many people are in your group? or are you traveling solo?", rows: 2 %>
      <%= text_field_tag :address, nil, placeholder: "Where are you based?" %>
      <%= hidden_field_tag :platform, identify_user_platform %>
      <%= button_tag "SUBMIT" %>
     </div>
  <% end %>
  </div>
</div>