config/routes.rb
Rails.application.routes.draw do

  @web = { domain: ["tripkada.com","localhost", "13.250.138.152", "13.229.186.20"] } unless Rails.env.development? || Rails.env.test?
  @api = { subdomain: ["staging-api","api"] } unless Rails.env.development? || Rails.env.test?

  mount Facebook::Messenger::Server, at: 'bot'
  mount Sidekiq::Web => "/sidekiq" # monitoring console
  constraints @api do
    mount API::Base => '/'
  end

  constraints @web do
    authenticate :user do

      scope :profile do
        post "/:slug/reviews",    to: "users#review",                   as: "profile_review"
        get "/:slug/edit",        to: "users#edit",                     as: "profile_edit"
        put "/:slug",             to: "users#update_profile_photos",    as: "profile_update"
        post "/:slug/follow",     to: "users#follow",                   as: "follow_user"
        delete "/:slug/unfollow", to: "users#unfollow",                 as: "unfollow_user"
      end

      scope :trips do
        get "/:slug/checkout",                                to: "event#checkout",                       as: "trip_checkout"
        get "/waitlists/:id/checkout",                        to: "event#waitlist_checkout",              as: "waitlist_checkout"
        get "/:slug/checkout/payment_details",                to: "event#payment_details",                as: "payment_details"
        get "/:slug/checkout/paypal_payment_verification",    to: "payments#paypal_payment_verification", as: "paypal_payment_verification"
        post "/:slug/join",                                   to: "event#join",                           as: "join"
        post "/:slug/join_using_promo_code",                  to: "event#join_using_promo_code",          as: "join_using_promo_code"
        post "/promo_code/validate",                          to: "promo_codes#validate",                 as: "validate_promo_code"
        post "/:slug/join_waitlist",                          to: "event#join_waitlist",                  as: "join_waitlist"
        get  "/:slug/checkout/dragonpay",                     to: "event#dragonpay",                      as: "dragonpay"
      end

      scope :organizer do
        get "/trips/:slug/edit",                      to: "event#edit",               as: "organizer_trip_edit"
        get "/trips/:slug/duplicate",                 to: "event#duplicate",          as: "organizer_trip_duplicate"
        put "/trips/:slug",                           to: "event#update",             as: "organizer_trips"
        delete "/trips/:slug",                        to: "event#destroy"
        get "/create_trip",                           to: "event#new"
        post "/create_trip",                          to: "event#create"
        put "/trip_no_show",                          to: "event#no_show",            as: "trip_no_show"
        scope :manage_trips do
          get "/",                                    to: "manage_trips#index",        as: "manage_trips"
          get "/my_trips",                            to: "manage_trips#trips",        as: "manage_trips_my_trips"
          get "/my_trips/:slug/waitlists",            to: "manage_trips#waitlists",    as: "manage_trips_waitlist"
          put "/my_trips/:slug/cancel",               to: "manage_trips#cancel_trip",  as: "organizer_trip_cancel"
          get "/joiner",                              to: "manage_trips#joiner",       as: "manage_trips_joiner"
          get "/payments",                            to: "manage_trips#payments",     as: "manage_trips_payments"
          get "/funds",                               to: "manage_trips#funds",        as: "manage_trips_funds"
          post "/invite_joiner",                      to: "manage_trips#invite_joiner", as: "organizer_invite_joiner"
          post "/invite_joiner_via_email",            to: "manage_trips#invite_joiner_via_email", as: "organizer_invite_joiner_via_email"
          get "organized_trip_views",                 to: "manage_trips#organized_trip_views"
          get "organized_trip_bookings",              to: "manage_trips#organized_trip_bookings"
          get "monthly_organized_trips",                      to: "manage_trips#monthly_organized_trips"
          get "monthly_organized_trips_booking_count",        to: "manage_trips#monthly_organized_trips_booking_count"

          post 'my_trips/waitlists/update_waitlist',  to: "manage_trips#update_waitlist", as: "update_waitlist"
        end
      end

      scope :admin do
        get "/",                                            to: "admin#index",                                     as: "admin"
        get "/event/:slug",                                 to: "admin#event",                                     as: "get_event"
        get "/users",                                       to: "users#index"
        get "/users/organizer_applicants",                  to: "users#organizer_applicants",                      as: "organizer_applicants"
        get "/users/export_all_organizers",                 to: "users#export_all_organizers",                     as: "export_all_organizers"
        get "/users/export_stats_organizer",                to: "users#export_stats_organizer",                    as: "export_stats_organizer"
        get "/users/cities",                                to: "users#cities"
        get "/users/export",                                to: "users#export",                                    as: "export_users"
        get "/users/segmentations",                         to: "users#segmentations",                             as: "user_segmentations"
        get "/users/export_segmentations",                  to: "users#export_segmentations",                      as: "export_users_segmentation"
        get "/payments/export_all_payments",                to: "payments#export_all_payments",                    as: "export_all_payments"
        get "/users/user_info",                             to: "users#user_info",                                 as: "user_info"
        get "/payments/mark_expired",                       to: "payments#mark_dragonpay_as_expired",              as: "mark_expired_payments"

        delete "/remove_joiner",                            to: "admin#remove_joiner"
        put "/users/:id/update_role",                       to: "users#update_role",                               as: "update_role"
        put "/event/featured",                              to: "admin#make_featured",                             as: "make_featured"
        get "/mailerlite/groups",                           to: "mailerlite#index",                                as: "mailerlite_groups"
        post "/mailerlite/groups",                          to: "mailerlite#create",                               as: "mailerlite_new_group"
        post "/mailerlite/groups/:id/import_subscribers",   to: "mailerlite#import_subscribers",                   as: "mailerlite_import_subscribers"
        delete "/mailerlite/groups/:id",                    to: "mailerlite#delete",                               as: "mailerlite_delete_group"
        post "/notifications/:id/deliver",                  to: "custom_notification_messages#deliver",            as: "deliver_notification"
        post "/promo_code/import",                          to: "promo_codes#import",                              as: "import_promo_code"

        resources :payments, only: [:index,:update]
        resources :app_versions, except: [:new]
        resources :promo_codes
        resources :categories
        resources :destinations
        resources :custom_notification_messages
        resources :booking_fees, only: [:index,:create]
        resources :referral_incentives, only: [:index,:create]
      end

      scope :payment do
        post "paypal_transaction",  to: "payments#paypal_transaction"
      end

      scope :user do
        get "/notifications",           to: "notifications#index"
        put "/notifications/:id",       to: "notifications#show",                             as: "user_notification"
        get "/notification_count",      to: "notifications#count_users_unseen_notifications", as: "count_unseen_notifications"
        put "/profile_update",          to: "users#update"
      end

      scope :referral do
        post "send_email_invitations",                  to: "referrals#send_invitations",      as: "send_referral_email_invitations"
      end

      scope :instagram do
        get "(/:provider_id)/connect",  to: "instagram#connect",      as: "instagram_connect"
        get "/callback",                to: "instagram#callback",     as: "instagram_callback"
      end

      get "/:role/my_trips",            to: "event#my_trips",       as: "my_trips"
      post "/become_a_trip_organizer",      to: "home#create_form_organiser"
    end

    root "home#index"
    get "profile/:slug/trips",                            to: "users#trips",                   as: "profile_trips"
    get "profile/:slug/reviews",                          to: "users#reviews",                 as: "profile_reviews"
    get "/trips_per_page",                                to: "event#paginated_page"
    get "/paginated_trips",                               to: "users#paginated_trips"
    get "/paginated_reviews",                             to: "users#paginated_reviews"
    get "/trips/:slug",                                   to: "event#page",                    as: "trip_view"
    get "/trips/:slug/joiners",                           to: "event#joiners",                 as: "trip_joiners"
    get "/trips/:slug/checkout/invited_payment_details",  to: "event#invited_payment_details", as: "invited_payment_details"
    get "/who_we_are",                                    to: "home#who_we_are"
    get "/how_it_works",                                  to: "home#how_it_works"
    get "/privacy_policy",                                to: "home#privacy_policy"

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string           not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :categorizations, foreign_key: :category_id, dependent: :destroy
  has_many :events, through: :categorizations

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :ensure_admin, except: [:validate], if: :user_signed_in?
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  set_tab :categories

  # GET /categories
  def index
    @categories = CategoryDecorator.search(params[:q]).page(params[:page]).per(10)
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully deleted.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id]).decorate
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:name, :active)
  end
end

app/views/categories/_categories.html.erb
<% if @categories.blank? %>
  <span class="alert label">No found match.</span>
<% else %>
<table class="category-list">
  <thead>
    <tr>
      <th>Category</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.decorate.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= validate_status_and_class(category) %></td>
        <td>
          <div class="button-group margin-0">
            <%= link_to icon('file'), category_path(category), class: "button info" %>
            <%= link_to icon('pencil'), edit_category_path(category), class: "button success" %>
            <%= link_to icon('trash'), category, method: :delete, data: { confirm: 'Are you sure?' }, class: "button alert" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.label :name, "Category:", class: "input-label" %>
  <%= f.input :name, placeholder: "e.g. Surfing", label: false %>
  <p></p>
  <div class="activation">
  <p>Activate Category</p>
    <div class="switch tiny">
      <%= f.check_box :active, checked: @category.active?, id: "categoryAvailability", class: "switch-input" %>
      <label class="switch-paddle" for="categoryAvailability">
        <span class="show-for-sr">Activate the category?</span>
        <span class="switch-active" aria-hidden="true">Yes</span>
        <span class="switch-inactive" aria-hidden="true">No</span>
      </label>
    </div>
  </div>
</div>

<div class="form-actions">
  <%= f.button :submit, "Save", class: "button" %>
</div>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, "Update Category") %>

<div class="header">
  <%= link_to "<span class='ion-chevron-left'></span> Back".html_safe, categories_path %>
  <h1>EDIT CATEGORY</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>

<div class="header">
  <h1>CATEGORIES</h1>
  <%= form_tag categories_path, method: :get, remote: true do %>
    <%= text_field_tag :q, nil, placeholder: "Search", autocomplete: :off , "data-submit-form" => "" %>
  <% end %>
</div>

<div id="categoryLists">
  <%= render "categories" %>
</div>

<div id="paginator">
  <%= paginate @categories, remote: true %>
</div>

<%= link_to 'ADD CATEGORY', new_category_path, class: "category-btn new" %>

app/views/categories/index.js.erb
$("#categoryLists").html("<%= escape_javascript(render("categories")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@categories, remote: true)) %>");

app/views/categories/new.html.erb
<% provide(:title, "New Category") %>

<div class="header">
  <%= link_to "<span class='ion-chevron-left'></span> Back".html_safe, categories_path %>
  <h1>NEW CATEGORY</h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<% provide(:title, "View Category") %>

<div class="header">
  <%= link_to "<span class='ion-chevron-left'></span> Back".html_safe, categories_path %>
  <h1>CATEGORIES</h1>
</div>

<div class="category-usage">
  <p>
    <span>Category:</span>
    <span><%= @category.name %></span>
  </p>
  <%= link_to 'Edit', edit_category_path(@category), class: "category-btn edit" %> 

</div>